import React from "react";
import style from "../styles/Content.module.css";
import { Link } from "react-router-dom";

export default function Content() {
  return (
    <div className={style.container}>
      <div className={style.menu}>
        <nav>
          <Link to="universities" className={style.link}>Universities</Link>
          <Link to="schools" className={style.link}>Schools</Link>
          <Link to="lyceums" className={style.link}>Lyceums</Link>
        </nav>
      </div>

      <div className={style.rightSide}>
        //filter box - component will be written



        //content generated by selection from the menu - router set up, component selection

      </div>


    </div>
  );
}
