import React from "react";
import style from "../styles/Content.module.css";
import { Link } from "react-router-dom";
import { useState } from "react";
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import GeneratedUnis from "../components/GeneratedUnis";
import GeneratedSchools from "../components/GeneratedSchools";
import GeneratedLyceums from "../components/GeneratedLyceums";
import UniFilter from "../components/UniFilter";
import SchoolFilter from "../components/SchoolFilter";
import LyceumFilter from "../components/LyceumFilter";

export default function Content() {
  const [uniClicked, setUniClicked] = useState(false);
  const [schoolClicked, setSchoolClicked] = useState(false);
  const [lyceumClicked, setLyceumClicked] = useState(false);

  function handleUniClick() {
    setUniClicked(true);
    setSchoolClicked(false);
    setLyceumClicked(false);
  }

  function handleSchoolClick() {
    setUniClicked(false);
    setSchoolClicked(true);
    setLyceumClicked(false);
  }

  function handleLyceumClick() {
    setUniClicked(false);
    setSchoolClicked(false);
    setLyceumClicked(true);
  }

  return (
    <div className={style.container}>
      <div className={style.menu}>
        <nav>
          <Link
            to="universities"
            className={style.link}
            onClick={handleUniClick}
            style={{
              backgroundColor: uniClicked ? "rgb(190, 116, 6)" : "beige",
            }}
          >
            Universities
          </Link>
          <Link
            to="schools"
            className={style.link}
            onClick={handleSchoolClick}
            style={{
              backgroundColor: schoolClicked ? "rgb(190, 116, 6)" : "beige",
            }}
          >
            Schools
          </Link>
          <Link
            to="lyceums"
            className={style.link}
            onClick={handleLyceumClick}
            style={{
              backgroundColor: lyceumClicked ? "rgb(190, 116, 6)" : "beige",
            }}
          >
            Lyceums
          </Link>
        </nav>
      </div>

      <div className={style.rightSide}>
        {/* filter box - component will be written */}

        <div className={style.filterBox}>
        <Routes>
            <Route path="/universities" element={< UniFilter/>} />
            <Route path="/schools" element={<SchoolFilter/>} />
            <Route path="/lyceums" element={<LyceumFilter />} />
          </Routes>
        </div>

        {/* content generated by selection from the menu - router set up, component selection */}

        <div className={style.generatedContent}>
          <Routes>
            <Route path="/universities" element={< GeneratedUnis/>} />
            <Route path="/schools" element={<GeneratedSchools/>} />
            <Route path="/lyceums" element={<GeneratedLyceums />} />
          </Routes>
        </div>
      </div>
    </div>
  );
}
